### 一、异常和错误

#### 1.概念

> ​	Python有两种错误很容易辨认：语法错误和异常
>
> ​	Python 的语法错误或者称之为解析错误，是初学者经常碰到的，比如缺少冒号等
>
> ​	在程序运行过程中，总会遇到各种各样的错误，有的错误是程序编写有问题造成的，这种错误我们通常称之为bug，bug是必须修复的；有的错误是用户输入造成的，这种错误可以通过检查用户输入来做相应的处理；还有一类错误是完全无法在程序运行过程中预测的，比如写入文件的时候，磁盘满了，写不进去了，或者从网络抓取数据，网络突然断掉了，这类错误被称为异常，在程序中通常是必须处理的，否则，程序会因为各种问题终止并退出
>

#### 2.常见异常【面试题】

> 【面试题】列出Python中常见的异常，至少5种
>
> AttributeError 试图访问一个对象没有的树形，比如foo.x，但是foo没有属性x
> IOError 输入/输出异常；基本上是无法打开文件
> ImportError 无法引入模块或包；基本上是路径问题或名称错误
> IndentationError 语法错误（的子类） ；代码没有正确对齐
> IndexError 下标索引超出序列边界，比如当x只有三个元素，却试图访问x[5]
> KeyError 试图访问字典里不存在的键
> KeyboardInterrupt Ctrl+C被按下
> NameError 使用一个还未被赋予对象的变量
> SyntaxError Python代码非法，代码不能编译(个人认为这是语法错误，写错了）
> TypeError 传入对象类型与要求的不符合
> UnboundLocalError 试图访问一个还未被设置的局部变量，基本上是由于另有一个同名的全局变量，
> 导致你以为正在访问它
> ValueError 传入一个调用者不期望的值，即使值的类型是正确的
>
> ```Python
>
> ```

#### 3.异常处理方式【重点掌握】

> 处理异常的本质：没有从根本上解决问题【修改代码】，只是将异常忽略，可以让后面的代码继续执行

##### 3.1try-except-finally/else捕获【常用】

> ```Python
> # 异常处理的方式：try-except   raise   assert
>
> """
> print('start')
> try:
>     可能存在异常的代码
> except 错误码 as 变量:
>     出现异常异常之后的提示
>
> print("end")
> """
>
> """
> 说明：
>     1.将可能存在异常的代码书写到try代码块中
>     2.如果try中的代码存在异常，try中的代码会执行到异常处，然后直接执行except分支
>     3.如果try中的代码不存在异常，try中的代码会执行完毕，然后直接执行try-except后面的语句
> """
>
> # index = int(input("请输入一个数字："))
> # list1 = [23,5,7,8]
> # num = list1[index]
> # print(f"列表中的第{index}个元素为:{num}")
>
>
> # 1.            *******
> """
> print("start")
> try:
>     # 可能存在异常的代码
>     index = int(input("请输入一个数字："))
>     print(index)
> # 注意1：e只是一个变量名，可以是任意一个合法的标识符，但是，常用e，异常：Exception
> # 注意2：e指向的是出现异常的对象，该异常对象的类型是ValueError
> except ValueError as e:
>     print(type(e))  # <class 'ValueError'>
>     # 注意3：打印一个对象，默认输出该对象的地址，但是，打印异常对象的时候，输出的是异常的描述信息，
>     # 则说明异常类中已经重写了__str__
>     print("出现了异常：",e)
> print("end")
> """
>
> # 2.     *******
> """
> 注意4：如果有多个except，每次只会执行其中的一个except代码块
> 注意5：执行顺序，如果try中的代码出现异常，从上往下依次遍历except分支，找到和出现的异常相匹配的except
> """
> # try:
> #     index = int(input("请输入一个数字："))
> #     list1 = [23,5,7,8]
> #     num = list1[index]
> #     print(f"列表中的第{index}个元素为:{num}")
> # except IndexError as e:
> #     print("IndexError:",e)
> # except ValueError as e:
> #     print("ValueError：",e)
> # print('over')
>
> # 3.
> """
> 注意6：异常的父类为Exception,Exception的父类为BaseException，可以捕获任意异常
> 注意7：如果不确定异常的具体类型，则可以使用异常的父类进行捕获
> """
> # try:
> #     index = int(input("请输入一个数字："))
> #     list1 = [23,5,7,8]
> #     num = list1[index]
> #     print(f"列表中的第{index}个元素为:{num}")
> # except Exception as e:    # 多态
> #     print(type(e))  # <class 'ValueError'>
> #     print("Exception:",e)
> #
> # print('over')
>
>
> # 4.
> # 注意8：如果不指名异常的类型，只是标记出现了异常，但是无法查看异常的具体描述信息
> # try:
> #     index = int(input("请输入一个数字："))
> #     list1 = [23,5,7,8]
> #     num = list1[index]
> #     print(f"列表中的第{index}个元素为:{num}")
> # except:
> #     print("出现了异常~~~")
> #
> # print('over')
>
> # # 5.也可以指定异常的范围
> # try:
> #     index = int(input("请输入一个数字："))
> #     list1 = [23,5,7,8]
> #     num = list1[index]
> #     print(f"列表中的第{index}个元素为:{num}")
> # except (TypeError,IndexError,ValueError,NameError,ImportError):
> #     print("出现了异常~~~")
> #
> # print('over')
>
> # 6.try-except-else
> # 注意9：try-except-else，只有当try中的代码没有异常的时候，else才会被执行
> # try:
> #     index = int(input("请输入一个数字："))
> #     list1 = [23,5,7,8]
> #     num = list1[index]
> #     print(f"列表中的第{index}个元素为:{num}")
> # except IndexError as e:
> #     print("IndexError:",e)
> # except ValueError as e:
> #     print("ValueError：",e)
> # else:
> #     print("else被执行了")
> # print('over')
>
>
> # 练习
> # try:
> #     f = open(r"file1.txt",'r',encoding='utf-85345')
> # except FileNotFoundError as e:
> #     print("文件不存在：",e)
> # except ValueError as e:
> #     print("打开模式错误：",e)
> # except LookupError as e:
> #     print("编码格式错误：",e)
> # else:
> #     # 只有当文件正常被打开了，才会执行read
> #     print(f.read())
>
> # 7.try-except-finally
> # 注意10：try-except-finally，无论try中代码是否存在异常，finally分支都会被执行
> # 所以finally常用于程序执行完毕的清理行为，如：关闭文件，关闭数据库等
> # try:
> #     index = int(input("请输入一个数字："))
> #     list1 = [23,5,7,8]
> #     num = list1[index]
> #     print(f"列表中的第{index}个元素为:{num}")
> # except IndexError as e:
> #     print("IndexError:",e)
> # except ValueError as e:
> #     print("ValueError：",e)
> # finally:
> #     print("finally被执行了")
> # print('over')
>
> # 练习：
> # f = None
> # try:
> #     f = open(r"file1.txt",'r',encoding='gbk')
> #     print(f.read())
> # except FileNotFoundError as e:
> #     print("文件不存在：",e)
> # except ValueError as e:
> #     print("打开模式错误：",e)
> # except LookupError as e:
> #     print("编码格式错误：",e)
> # finally:
> #     if f:
> #         f.close()
> #         print("文件关闭成功")
>
> # 【面试题】代码阅读题
> # 注意11：在try或except中出现return，finally仍然会被执行
> def func():
>     try:
>         index = int(input("请输入一个数字："))
>         list1 = [23,5,7,8]
>         num = list1[index]
>         print(f"列表中的第{index}个元素为:{num}")
>         return
>     except IndexError as e:
>         print("IndexError:",e)
>         return
>     except ValueError as e:
>         print("ValueError：",e)
>     finally:
>         print("finally被执行了")
> func()
> ```

##### 3.2raise抛出

> ```Python
> """
> 异常对象出现的表现形式：
>     a.根据具体的问题出现，将会产生一个异常对象
>     b.根据异常的类创建一个异常的对象
> """
>
> # 1.可能性
> # try:
> #     index = int(input("请输入一个数字："))   # abc
> # except ValueError as e:
> #     print(e)
>
> # 2.一定
> # 注意：raise一般应用于自定义异常中
> try:
>     e = ValueError("出现了异常")  # 创建一个异常对象
>     raise e     # 抛出异常对象
> except ValueError as e:
>     print(e)
> ```

##### 3.3assert断言

> ```Python
> # assert:断言/预言
>
>
> # 1
> # def div(a,b):
> #     return a / b
> # try:
> #     r = div(10, 0)
> #     print(r)
> # except ZeroDivisionError as e:
> #     print(e)
>
> # 2
> def div(a,b):
>     # assert 条件语句,异常出现的描述信息
>     # 工作原理：如果预测成功，则代码正常执行，如果预测失败，则会抛出一个新的断言异常AssertionError
>     assert b != 0,"b参数不能为0"
>     return a / b
>
> r = div(10, 0)
> print(r)
>
> # 工作原理
> def div(a,b):
>     if b != 0:
>         return a / b
>     else:
>         raise AssertionError("b参数不能为0")
>
> # 使用场景：在一定情况下，可以代替if语句
> ```

#### 4.自定义异常

> ```Python
>
> # 【面试题】
> # 1.自定义异常类的实现步骤
> # a.自定义一个类，继承自Exception/BaseException
> class MyException(Exception):
>     # b.定义构造函数__init__，调用父类的构造函数，并定义一个实例属性，表示异常的描述信息
>     def __init__(self,msg):
>         super().__init__()
>         self.msg = msg
>
>     # c.重写__str__,返回异常的描述信息字符串
>     def __str__(self):
>         return self.msg
>
>     # d.定义一个实例函数，用于处理出现的异常
>     def handle(self):
>         print("处理了异常~~~")
>
> try:
>     raise  MyException("出现了异常")
> except MyException as e:
>     print(e)
>     e.handle()
>
> # 注意：如果需要处理生活中的问题，则可以通过自定义异常操作
>
> # 2.案例
> # 需求：自定义一个异常，表示上班迟到的异常，如果8点之前起床，上班不会迟到，如果8点之后起床，上班会迟到
> class LateException(Exception):
>     __slots__ = ("message",)
>     def __init__(self,message):
>         super().__init__()
>         self.message = message
>     def __str__(self):
>         return self.message
>     def handle(self):
>         print("延迟下班时间")
>
> time = float(input("请输入起床时间："))
> if time > 8:
>     # 出现异常
>     try:
>         raise LateException("最近上班太累，闹铃响了没听见")
>     except LateException as e:
>         print("迟到的原因：",e)
>         e.handle()
> else:
>     print("早早到达公司，开始搬砖~~~")
> ```
